name: QA Tranzit

on:
  push:
  pull_request:

jobs:
  qa:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.1', '8.2']
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: pdo, pdo_mysql, mysqli, mbstring
          coverage: xdebug
      - run: composer install --no-progress --prefer-dist
      - run: composer cs:check
      - run: composer stan
      - run: composer psalm
      - run: composer test
